### ISSUE TITLE
March 5, 2020 | Code-Review : The Poodles

### ISSUE THREAD

**Issue by jabichris** [sz16900/tic-tac-toe-ruby#3]
Nice work team. Keep up the good work

**Comment by Flakster** [comment]
It is a good idea to split methods with a big number of comparisons into several others to manage the "perceived complexity" and that stuff @sz16900 . Now you have to break down that big file into classes and modules. Great job!

**Comment by sz16900** [comment]
Thanks for the suggestion guys, will keep this in mind as we move into the next Milestone.
